try {
    let a;
    console.log(a.length);
} catch (e) {
    console.log("inside a catch statement");
}

console.log("Hi there");